// Package schemes provides a collection of constants and lists representing URL schemes.
// URL schemes, also known as URI schemes, define how resources on the internet or other
// networks are accessed. They act as prefixes in URLs, indicating the protocol or service
// to be used (e.g., "http", "ftp", "mailto").
//
// This package includes the following:
//  1. **Official IANA Schemes**: A list of schemes officially registered and managed by IANA (Internet Assigned Numbers Authority).
//  2. **Unofficial Schemes**: A list of widely used but unofficial schemes commonly associated with specific software or services.
//  3. **No Authority Schemes**: A list of schemes that do not require an authority component (i.e., they are followed by ":" instead of "://").
//
// The lists are autogenerated from official sources, including IANA, and may include additional unofficial schemes
// for software interoperability and network services.
package schemes
